### ISSUE TITLE
Crash during initialization

### ISSUE THREAD

**Issue by polysillycon** [blay09/EiraMoticons#43]
In the Project Ozone 2 Reloaded mod-pack, your mod crashed during initialization.

java.lang.NullPointerException: Initializing game
    at net.blay09.mods.eiramoticons.addon.pack.TwitchTurboPack.<init>(TwitchTurboPack.java:54)
    at net.blay09.mods.eiramoticons.ClientProxy.reloadEmoticons(ClientProxy.java:98)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_948_ClientProxy_reloadEmoticons_ReloadEmoticons.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    . . . 

Full crash report here:   http://pastebin.com/pB2BaQqc

**Comment by BlayTheNinth** [comment]
Disable Twitch turbo emotes or update to latest version. Seems like the twitchemotes.com API removed the turbo set.
